// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWk7a7k13-MMEUNZ_2vZEbV8dS6DwbCL4',
    appId: '1:953009996983:web:58b7c0291d6f3f30aeb932',
    messagingSenderId: '953009996983',
    projectId: 'attendance-management-sy-3d1cc',
    authDomain: 'attendance-management-sy-3d1cc.firebaseapp.com',
    storageBucket: 'attendance-management-sy-3d1cc.appspot.com',
    measurementId: 'G-2W57KN1HJ7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDu1x_09nEtAWmyB5mb2GgyUEtu-i9KXtg',
    appId: '1:953009996983:android:1777a26a12864d02aeb932',
    messagingSenderId: '953009996983',
    projectId: 'attendance-management-sy-3d1cc',
    storageBucket: 'attendance-management-sy-3d1cc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAn5jbD6YS_KEfrqSA-GPGHIyuVLCQAwyo',
    appId: '1:953009996983:ios:5026e2adc11d281caeb932',
    messagingSenderId: '953009996983',
    projectId: 'attendance-management-sy-3d1cc',
    storageBucket: 'attendance-management-sy-3d1cc.appspot.com',
    iosBundleId: 'com.example.loginpage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAn5jbD6YS_KEfrqSA-GPGHIyuVLCQAwyo',
    appId: '1:953009996983:ios:79bccdd99143d890aeb932',
    messagingSenderId: '953009996983',
    projectId: 'attendance-management-sy-3d1cc',
    storageBucket: 'attendance-management-sy-3d1cc.appspot.com',
    iosBundleId: 'com.example.loginpage.RunnerTests',
  );
}
